packages:
  - "backend"
  - "apps/*"
  - "shared"
allowBuilds:
  '@prisma/client': false
  '@prisma/engines': false
  '@railway/cli': set this to true or false
  bcrypt: false
  esbuild: false
  msgpackr-extract: false
  prisma: false
  sharp: false
  unrs-resolver: false
